services:
  postgres:
    image: postgres:16
    container_name: mygoods-postgres
    environment:
      POSTGRES_DB: mygoods
      POSTGRES_USER: mygoods
      POSTGRES_PASSWORD: mygoods
    ports:
      - "5432:5432"
    volumes:
      - mygoods-pgdata:/var/lib/postgresql/data

volumes:
  mygoods-pgdata:
